### ISSUE TITLE
Esc-Menu nicht funktionstüchig

### ISSUE THREAD

**Issue by Wolfonye** [soraphis/HorrorOma#30]
Tritt bei Verwendung nicht-nativer Monitorauflösung auf.

Getestet mit:

Monitorauflösung: 1920x1080
Ingame-Auflösung: 1152x648

**Comment by soraphis** [comment]
fühlt sich nach [dieser issue](https://issuetracker.unity3d.com/issues/full-screen-input-dot-mouseposition-output-does-not-match-the-displayed-view-on-the-screen) hier an.

sollte jedoch eigentlich in unity 5.2 behoben worden sein, aktueller build ist auf 5.3 :/
mal nachschauen.

**Comment by soraphis** [comment]
dem ganzen hinzuzufügen ist: UI skaliert schlecht mit non-native auflösungen bei vollbild, wobei ich natürlich verrückt finde bei einem full-hd monitor in vollbild mit einer geringeren auflösung zu spielen :/

**Comment by soraphis** [comment]
Okay, auf unity version 5.5. geht das ganze. und verhällt sich wie gedacht.
